import collections

BANK_OPERATIONS = [
    "TRANSFER", "TRANSFER COMMISSION","TRANSFER BETWEEN CUSTOMERS","CONTRIBUTION",
    "TAX","SALARY", "VAT", "WEB PURCHASE", "POS/WEB",
    "AIRTIME", "PURCHASE", "INSTANT PAYMENT",
    "CASH","WITHDRAWAL", "ATM", "SMS ALERT CHARGE",
    "FAILED", "FUNDS", "FAILED","FUNDS","LOAN","INTEREST",
    "GTWORLD", "LOANDISBURSEMENT"
    ]

DTI_EARNERS = {
    "LOW_EARNER": 0.33,
    "LOW_MED_EARNER": 0.35,
    "MED_EARNER": 0.40,
    "HIGH_MED_EARNER": 0.45,
    "HIGH_EARNER": 0.5,
    "TOP_EARNER": 0.55
}
BRACKET_COLORS =  {
    "LOW_EARNER": "red",
    "LOW_MED_EARNER": "orange",
    "MED_EARNER": "yellow",
    "HIGH_MED_EARNER": "green",
    "HIGH_EARNER": "blue",
    "TOP_EARNER": "blue"
}