AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-aws-lambda-classify

Parameters:
  ImageUriParameter:
    Type: String
    Default: 144475594127.dkr.ecr.eu-west-1.amazonaws.com/liberta_classification:latest
    Description: Enter arn of the ecr repository
  ImageNameParameter:
    Type: String
    Default: yet-another-docker-image
    Description: Enter arn of the ecr repository
  TimeOutParameter:
    Type: Number
    Default: 60
    Description: Enter the timeout value for the lambda function
  MemorySizeParameter:
    Type: Number
    Default: 7000
    Description: Enter the memory value for the lambda function 
    

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: {"Ref" : "TimeOutParameter" }
    MemorySize: {"Ref" : "MemorySizeParameter" }
    Environment: 
      Variables: 
        output_bucket_name: liberta-leasing-ml
        output_file_name: classified_dataframe.xlsx

Resources:
  MyCustomDocker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: { "Ref" : "ImageNameParameter" }
      ImageUri: { "Ref" : "ImageUriParameter" }
      PackageType: Image
      Role: arn:aws:iam::144475594127:role/service-role/transaction_classify-role-r8f7vzng
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /classificazione
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyCustomDockerApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classificazione/'
